/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.aderessbook;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.text.html.HTML.Tag.OPTION;

/**
 *
 * @author smart
 */
public class AderessBook extends javax.swing.JFrame {

    ArrayList<Data> adresses = new ArrayList<>();

//    /**
//     * Creates new form Dataadressbook
//     */
    public AderessBook() {
        initComponents();
        contactPersonDatajLabel.setVisible(!personRadioButton.isSelected());
    }
    public void search () {
        String[] empty = new String[0];
        searchRes.setListData(empty);
        String searchParams = searchAbout.getText();
        System.out.println(searchParams);
        ArrayList<Data> searchResults = new ArrayList<>();
        for (Data d : adresses) {
            if (d instanceof Person) {
                Person p = (Person) d;
                if (p.compareBy(searchParams)) {
                    searchResults.add(p);
                }
            }
            if (d instanceof Bussinesses) {
                Bussinesses b = (Bussinesses) d;
                if (b.compareBy(searchParams)) {
                    searchResults.add(b);
                }
            }
        }
        String[] searchResultsList = new String[searchResults.size()];
        for (int i = 0; i < searchResults.size(); i++) {
            if (searchResults.get(i) instanceof Person) {
                Person p = (Person) searchResults.get(i);
                searchResultsList[i] = p.getFirst() + ' ' + p.getLast();
            }
            if (searchResults.get(i) instanceof Bussinesses) {
                Bussinesses b = (Bussinesses) searchResults.get(i);
                searchResultsList[i] = b.getTitle();
            }
        }
        System.out.println(searchResults.size());
        searchRes.setListData(searchResultsList);

    }

    public void isEmptyTextField() throws EmptyTextFieldException {

        if (!((businessRadioButton.isSelected() && (titleTextField.getText().isEmpty() || generTextField.getText().isEmpty()
                || websiteTextField.getText().isEmpty())) || (firstNameTextField.getText().isEmpty()
                || lastNameTextField.getText().isEmpty() || dayTextField.getText().isEmpty()
                || monthTextField.getText().isEmpty() || yearTextField.getText().isEmpty()
                || countryComboBox.getSelectedItem() == "Country" || cityComboBox.getSelectedItem() == "City")
                || postalCodeTexField.getText().isEmpty() || emailTextField.getText().isEmpty()
                || telephoneNumberTExtField.getText().isEmpty())) {

        } else {
            throw new EmptyTextFieldException(
                    "Please Fill All Information"
            );
        }
    }

    public String emailChecked(String email) throws invalidEmailFormatException {
        if ((email.endsWith(".com")) && (email.contains("@"))) {
            return email;
        } else {
            throw new invalidEmailFormatException(
                    "Email Must Contain (@) and Ends with (.com)"
            );
        }
    }

    public String postalCodeChecked(String postalCode) throws invalidPostalCodException {
        if (postalCode.length() == 4) {
            return postalCode;
        } else {
            throw new invalidPostalCodException(
                    "Postal code must be 4 digit"
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adressButtonGroup = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        search = new javax.swing.JPanel();
        searchAbout = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchRes = new javax.swing.JList<>();
        person = new javax.swing.JPanel();
        LfirstName = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        LlastName1 = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        birthdayl = new javax.swing.JLabel();
        dayTextField = new javax.swing.JTextField();
        monthTextField = new javax.swing.JTextField();
        yearTextField = new javax.swing.JTextField();
        Lday = new javax.swing.JLabel();
        lmonth = new javax.swing.JLabel();
        lyear = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lcountry = new javax.swing.JLabel();
        countryComboBox = new javax.swing.JComboBox<>();
        lcity = new javax.swing.JLabel();
        cityComboBox = new javax.swing.JComboBox<>();
        lpostal = new javax.swing.JLabel();
        postalCodeTexField = new javax.swing.JTextField();
        lemail = new javax.swing.JLabel();
        generTextField = new javax.swing.JTextField();
        lTelephone = new javax.swing.JLabel();
        telephoneNumberTExtField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        websiteTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        titleTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        personRadioButton = new javax.swing.JRadioButton();
        businessRadioButton = new javax.swing.JRadioButton();
        lcountry1 = new javax.swing.JLabel();
        bcountryComboBox1 = new javax.swing.JComboBox<>();
        lcity1 = new javax.swing.JLabel();
        btelephoneNumberTExtField1 = new javax.swing.JTextField();
        lTelephone1 = new javax.swing.JLabel();
        bemailTextField1 = new javax.swing.JTextField();
        lemail1 = new javax.swing.JLabel();
        lpostal1 = new javax.swing.JLabel();
        bpostalCodeTexField1 = new javax.swing.JTextField();
        bcityComboBox1 = new javax.swing.JComboBox<>();
        contactPersonDatajLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        saveMenuItem = new javax.swing.JMenuItem();
        OpenMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Address Book");

        searchAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAboutActionPerformed(evt);
            }
        });
        searchAbout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchAboutKeyPressed(evt);
            }
        });

        jLabel7.setText("Search here :");

        searchRes.setBorder(javax.swing.BorderFactory.createTitledBorder("Search results"));
        searchRes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                searchResValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(searchRes);

        javax.swing.GroupLayout searchLayout = new javax.swing.GroupLayout(search);
        search.setLayout(searchLayout);
        searchLayout.setHorizontalGroup(
            searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(221, 221, 221))
        );
        searchLayout.setVerticalGroup(
            searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(searchAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Search", search);

        LfirstName.setText("First name : ");

        lastNameTextField.setEnabled(false);

        LlastName1.setText("Last name : ");

        firstNameTextField.setEnabled(false);
        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });

        birthdayl.setText("Birthday:");

        dayTextField.setEnabled(false);

        monthTextField.setEnabled(false);

        yearTextField.setEnabled(false);
        yearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearTextFieldActionPerformed(evt);
            }
        });

        Lday.setText("Day");

        lmonth.setText("Month");

        lyear.setText("Year");

        lcountry.setText("Country :");

        countryComboBox.setEditable(true);
        countryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "country", "Palestine", "Jordan", "Iraq", "Kuwait", "Saudi Arabia", "Egypt", " ", " " }));
        countryComboBox.setEnabled(false);
        countryComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                countryComboBoxItemStateChanged(evt);
            }
        });

        lcity.setText("City :");

        cityComboBox.setEditable(true);
        cityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "City", "Hebron", "Ramallah", "Jericho", "Gaza", "Nablus", "Cairo", "Alexandria", "Luxor", "Hawally", "Fintas", "Al Jahra", "Al Farwaniyah", " " }));
        cityComboBox.setEnabled(false);
        cityComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cityComboBoxItemStateChanged(evt);
            }
        });

        lpostal.setText("Postal Code : ");

        postalCodeTexField.setEnabled(false);
        postalCodeTexField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postalCodeTexFieldActionPerformed(evt);
            }
        });

        lemail.setText("Email :");

        generTextField.setEnabled(false);

        lTelephone.setText("Telephone-Number");

        telephoneNumberTExtField.setEnabled(false);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        websiteTextField.setEnabled(false);

        jLabel3.setText("Title :");

        titleTextField.setEnabled(false);

        jLabel4.setText("Gener :");

        jLabel5.setText("Website :");

        emailTextField.setEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Adress Type : "));

        adressButtonGroup.add(personRadioButton);
        personRadioButton.setText("Person");
        personRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personRadioButtonActionPerformed(evt);
            }
        });

        adressButtonGroup.add(businessRadioButton);
        businessRadioButton.setText("Businiss ");
        businessRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                businessRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(261, Short.MAX_VALUE)
                .addComponent(personRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(businessRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personRadioButton)
                    .addComponent(businessRadioButton))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        lcountry1.setText("Country :");

        bcountryComboBox1.setEditable(true);
        bcountryComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "country", "Palestine", "Jordan", "Iraq", "Kuwait", "Saudi Arabia", "Egypt", " ", " " }));
        bcountryComboBox1.setEnabled(false);
        bcountryComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bcountryComboBox1ItemStateChanged(evt);
            }
        });

        lcity1.setText("City :");

        btelephoneNumberTExtField1.setEnabled(false);

        lTelephone1.setText("Telephone-Number");

        bemailTextField1.setEnabled(false);

        lemail1.setText("Email :");

        lpostal1.setText("Postal Code : ");

        bpostalCodeTexField1.setEnabled(false);
        bpostalCodeTexField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpostalCodeTexField1ActionPerformed(evt);
            }
        });

        bcityComboBox1.setEditable(true);
        bcityComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "City", "Hebron", "Ramallah", "Jericho", "Gaza", "Nablus", "Cairo", "Alexandria", "Luxor", "Hawally", "Fintas", "Al Jahra", "Al Farwaniyah", " " }));
        bcityComboBox1.setEnabled(false);
        bcityComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bcityComboBox1ItemStateChanged(evt);
            }
        });

        contactPersonDatajLabel.setText("Contact person's data :");

        javax.swing.GroupLayout personLayout = new javax.swing.GroupLayout(person);
        person.setLayout(personLayout);
        personLayout.setHorizontalGroup(
            personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personLayout.createSequentialGroup()
                .addGap(613, 613, 613)
                .addComponent(jSeparator2)
                .addGap(20, 20, 20))
            .addGroup(personLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personLayout.createSequentialGroup()
                        .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(personLayout.createSequentialGroup()
                                        .addComponent(lpostal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(postalCodeTexField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, personLayout.createSequentialGroup()
                                        .addComponent(lTelephone)
                                        .addGap(40, 40, 40)
                                        .addComponent(telephoneNumberTExtField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personLayout.createSequentialGroup()
                                    .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LlastName1)
                                        .addComponent(birthdayl, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lcity, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lcountry, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(76, 76, 76)
                                    .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(personLayout.createSequentialGroup()
                                            .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(dayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Lday, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(25, 25, 25)
                                            .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(monthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(personLayout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addComponent(lyear, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(personLayout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addComponent(countryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(personLayout.createSequentialGroup()
                                            .addGap(172, 172, 172)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(personLayout.createSequentialGroup()
                                            .addGap(168, 168, 168)
                                            .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lTelephone1)
                                                .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lemail1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lcity1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(lpostal1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(btelephoneNumberTExtField1, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(bemailTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(bcityComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, 158, Short.MAX_VALUE)
                                                .addComponent(bpostalCodeTexField1))))
                                    .addGap(35, 35, 35))
                                .addGroup(personLayout.createSequentialGroup()
                                    .addGap(505, 505, 505)
                                    .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton1)
                                        .addGroup(personLayout.createSequentialGroup()
                                            .addComponent(lcountry1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(54, 54, 54)
                                            .addComponent(bcountryComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(personLayout.createSequentialGroup()
                                .addComponent(LfirstName)
                                .addGap(81, 81, 81)
                                .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(172, 172, 172)
                                .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, personLayout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                                        .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, personLayout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)
                                        .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(generTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                            .addComponent(websiteTextField))))))
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(personLayout.createSequentialGroup()
                        .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lemail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contactPersonDatajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        personLayout.setVerticalGroup(
            personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(contactPersonDatajLabel)
                        .addGap(18, 18, 18)
                        .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LfirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(LlastName1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(personLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lmonth)
                                    .addComponent(Lday)
                                    .addComponent(lyear)
                                    .addComponent(jLabel5))))
                        .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(birthdayl)
                                .addGap(18, 18, 18)
                                .addComponent(lcountry)
                                .addGap(23, 23, 23))
                            .addGroup(personLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(monthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(countryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(personLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(29, 29, 29)
                        .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(generTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(websiteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bcountryComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lcountry1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bcityComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lcity1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)))
                .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personLayout.createSequentialGroup()
                        .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personLayout.createSequentialGroup()
                                .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(personLayout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(lemail1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(personLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(bemailTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lTelephone1)
                            .addComponent(btelephoneNumberTExtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(personLayout.createSequentialGroup()
                        .addComponent(lcity)
                        .addGap(18, 18, 18)
                        .addComponent(lemail)
                        .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lTelephone))
                            .addGroup(personLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(telephoneNumberTExtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lpostal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(postalCodeTexField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lpostal1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bpostalCodeTexField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Add Address", person);

        jMenu2.setText("File");

        saveMenuItem.setText("Save");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(saveMenuItem);

        OpenMenuItem.setText("Open");
        OpenMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(OpenMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void postalCodeTexFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postalCodeTexFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postalCodeTexFieldActionPerformed

    private void cityComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cityComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cityComboBoxItemStateChanged

    private void countryComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_countryComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_countryComboBoxItemStateChanged

    private void yearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTextFieldActionPerformed

    private void personRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personRadioButtonActionPerformed
        // TODO add your handling code here:
        contactPersonDatajLabel.setVisible(!personRadioButton.isSelected());
        bcountryComboBox1.setEnabled(businessRadioButton.isSelected());
        bcityComboBox1.setEnabled(businessRadioButton.isSelected());
        bemailTextField1.setEnabled(businessRadioButton.isSelected());
        bpostalCodeTexField1.setEnabled(businessRadioButton.isSelected());
        btelephoneNumberTExtField1.setEnabled(businessRadioButton.isSelected());
        firstNameTextField.setEnabled(personRadioButton.isSelected());
        lastNameTextField.setEnabled(personRadioButton.isSelected());
        dayTextField.setEnabled(personRadioButton.isSelected());
        monthTextField.setEnabled(personRadioButton.isSelected());
        yearTextField.setEnabled(personRadioButton.isSelected());
        countryComboBox.setEnabled(personRadioButton.isSelected());
        cityComboBox.setEnabled(personRadioButton.isSelected());
        emailTextField.setEnabled(personRadioButton.isSelected());
        postalCodeTexField.setEnabled(personRadioButton.isSelected());
        telephoneNumberTExtField.setEnabled(personRadioButton.isSelected());
        titleTextField.setEnabled(!personRadioButton.isSelected());
        generTextField.setEnabled(!personRadioButton.isSelected());
        websiteTextField.setEnabled(!personRadioButton.isSelected());
    }//GEN-LAST:event_personRadioButtonActionPerformed

    private void businessRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_businessRadioButtonActionPerformed
        // TODO add your handling code here:
        contactPersonDatajLabel.setVisible(businessRadioButton.isSelected());
        titleTextField.setEnabled(businessRadioButton.isSelected());
        generTextField.setEnabled(businessRadioButton.isSelected());
        websiteTextField.setEnabled(businessRadioButton.isSelected());
        countryComboBox.setEnabled(businessRadioButton.isSelected());
        cityComboBox.setEnabled(businessRadioButton.isSelected());
        emailTextField.setEnabled(businessRadioButton.isSelected());
        postalCodeTexField.setEnabled(businessRadioButton.isSelected());
        telephoneNumberTExtField.setEnabled(businessRadioButton.isSelected());
        firstNameTextField.setEnabled(businessRadioButton.isSelected());
        bcountryComboBox1.setEnabled(businessRadioButton.isSelected());
        bcityComboBox1.setEnabled(businessRadioButton.isSelected());
        bemailTextField1.setEnabled(businessRadioButton.isSelected());
        bpostalCodeTexField1.setEnabled(businessRadioButton.isSelected());
        btelephoneNumberTExtField1.setEnabled(businessRadioButton.isSelected());
        lastNameTextField.setEnabled(businessRadioButton.isSelected());
        dayTextField.setEnabled(businessRadioButton.isSelected());
        monthTextField.setEnabled(businessRadioButton.isSelected());
        yearTextField.setEnabled(businessRadioButton.isSelected());

    }//GEN-LAST:event_businessRadioButtonActionPerformed


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            if (personRadioButton.isSelected()) {
                String firstName = firstNameTextField.getText();
                String lastName = lastNameTextField.getText();
                int day = Integer.parseInt(dayTextField.getText());
                int month = Integer.parseInt(monthTextField.getText());
                int year = Integer.parseInt(yearTextField.getText());
                String country = countryComboBox.getSelectedItem().toString();
                String city = cityComboBox.getSelectedItem().toString();
                String postalCode = postalCodeTexField.getText();
                postalCode = postalCodeChecked(postalCode);
                String email = emailTextField.getText();
                email = emailChecked(email);
                String telephone = telephoneNumberTExtField.getText();
                BirthDate bd = new BirthDate(day, month, year);
                Person person = new Person(firstName, lastName, bd, country, city, email, postalCode, telephone);
                isEmptyTextField();
                adresses.add(person);
                firstNameTextField.setText("");
                lastNameTextField.setText("");
                dayTextField.setText("");
                monthTextField.setText("");
                yearTextField.setText("");
                countryComboBox.setSelectedIndex(0);
                cityComboBox.setSelectedIndex(0);
                postalCodeTexField.setText("");
                emailTextField.setText("");
                telephoneNumberTExtField.setText("");
                search();

            } else {
                String country = countryComboBox.getSelectedItem().toString();
                String city = cityComboBox.getSelectedItem().toString();
                String postalCode = postalCodeTexField.getText();
                postalCode = postalCodeChecked(postalCode);
                String email = emailTextField.getText();
                email = emailChecked(email);
                String telephone = telephoneNumberTExtField.getText();
                String bcountry = countryComboBox.getSelectedItem().toString();
                String bcity = cityComboBox.getSelectedItem().toString();
                String bpostalCode = postalCodeTexField.getText();
                bpostalCode = postalCodeChecked(bpostalCode);
                String bemail = emailTextField.getText();
                bemail = emailChecked(bemail);
                String btelephone = telephoneNumberTExtField.getText();
                String title = titleTextField.getText();
                String gener = generTextField.getText();
                String wibsite = websiteTextField.getText();
                String firstName = firstNameTextField.getText();
                String lastName = lastNameTextField.getText();
                int day = Integer.parseInt(dayTextField.getText());
                int month = Integer.parseInt(monthTextField.getText());
                int year = Integer.parseInt(yearTextField.getText());
                BirthDate bd = new BirthDate(day, month, year);
                Person person = new Person(firstName, lastName, bd, country, city, email, postalCode, telephone);
                Bussinesses bussinesses = new Bussinesses(title, gener, wibsite, person, bcountry, bcity, bemail, bpostalCode, btelephone);
                isEmptyTextField();
                adresses.add(bussinesses);
                firstNameTextField.setText("");
                lastNameTextField.setText("");
                dayTextField.setText("");
                monthTextField.setText("");
                yearTextField.setText("");
                countryComboBox.setSelectedIndex(0);
                cityComboBox.setSelectedIndex(0);
                postalCodeTexField.setText("");
                emailTextField.setText("");
                telephoneNumberTExtField.setText("");
                titleTextField.setText("");
                generTextField.setText("");
                websiteTextField.setText("");
                bcountryComboBox1.setSelectedIndex(0);
                bcityComboBox1.setSelectedIndex(0);
                bpostalCodeTexField1.setText("");
                bemailTextField1.setText("");
                btelephoneNumberTExtField1.setText("");
                search();
            }
        } catch (EmptyTextFieldException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (invalidEmailFormatException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (invalidPostalCodException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "invalid number format , couldn't add this address");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Something went wrong , couldn't add this address");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void searchAboutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchAboutKeyPressed
        // TODO add your handling code here:
//        String[] empty = new String[0];
//        searchRes.setListData(empty);
//        String searchParams = searchAbout.getText();
//        System.out.println(searchParams);
//        ArrayList<Data> searchResults = new ArrayList<>();
//        for (Data d : adresses) {
//            if (d instanceof Person) {
//                Person p = (Person) d;
//                if (p.compareBy(searchParams)) {
//                    searchResults.add(p);
//                }
//            }
//            if (d instanceof Bussinesses) {
//                Bussinesses b = (Bussinesses) d;
//                if (b.compareBy(searchParams)) {
//                    searchResults.add(b);
//                }
//            }
//        }
//        String[] searchResultsList = new String[searchResults.size()];
//        for (int i = 0; i < searchResults.size(); i++) {
//            if (searchResults.get(i) instanceof Person) {
//                Person p = (Person) searchResults.get(i);
//                searchResultsList[i] = p.getFirst() + ' ' + p.getLast();
//            }
//            if (searchResults.get(i) instanceof Bussinesses) {
//                Bussinesses b = (Bussinesses) searchResults.get(i);
//                searchResultsList[i] = b.getTitle();
//            }
//        }
//        System.out.println(searchResults.size());
//        searchRes.setListData(searchResultsList);
        search();
    }//GEN-LAST:event_searchAboutKeyPressed

    private void searchAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAboutActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_searchAboutActionPerformed

    private void searchResValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_searchResValueChanged
        // TODO add your handling code here:
        String selected = searchRes.getSelectedValue();
        for (Data d : adresses) {
            if (d instanceof Person) {
                Person p = (Person) d;
                if ((p.getFirst() + ' ' + p.getLast()).equals(selected)) {
                    JOptionPane.showMessageDialog(this, p.getInfo());
                    break;
                }
            }
            if (d instanceof Bussinesses) {
                Bussinesses b = (Bussinesses) d;
                if (b.getTitle().equals(selected)) {
                    JOptionPane.showMessageDialog(this, b.getInfo());
                    break;
                }
            }
        }

    }//GEN-LAST:event_searchResValueChanged

    private void bcountryComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bcountryComboBox1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_bcountryComboBox1ItemStateChanged

    private void bpostalCodeTexField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpostalCodeTexField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bpostalCodeTexField1ActionPerformed

    private void bcityComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bcityComboBox1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_bcityComboBox1ItemStateChanged

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        // TODO add your handling code here:
        File file = null;
        JFileChooser chooser = new JFileChooser(file);
        int returnVal = chooser.showSaveDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            file = chooser.getSelectedFile();
        }
        try {
            PrintWriter printWriter = new PrintWriter(file);
            for (int i = 0; i < adresses.size(); i++) {
                String str = adresses.get(i).fileFormat();
                printWriter.println(str);
            }
            printWriter.close();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void OpenMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenMenuItemActionPerformed
        // TODO add your handling code here:
        File file = null;
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            file = chooser.getSelectedFile();
        }
        Scanner scn;
        try {
            scn = new Scanner(file);
            adresses.clear() ;
            String [] str = new String[0] ;
            searchRes.setListData(str);
            while (scn.hasNext()) {
                String line = scn.nextLine();
                String[] data = line.split(":");
                if (data.length < 10) {
                    Person p = new Person();

                    p.setFirst(data[0].substring(0, data[0].indexOf(" ")));
                    p.setLast(data[0].substring(data[0].indexOf(" ")));
                    p.setBirthDate(new BirthDate());
                    p.getBirthDate().setDay(Integer.parseInt(data[1]));
                    p.getBirthDate().setMonth(Integer.parseInt(data[2]));
                    p.getBirthDate().setYear(Integer.parseInt(data[3]));
                    p.setEmail(data[4]);
                    p.setTelNum(data[5]);
                    p.setCountry(data[6]);
                    p.setCity(data[7]);
                    p.setPostal(data[8]);
                    adresses.add(p);
                } else {
                    Bussinesses b = new Bussinesses() ;
                    b.setTitle(data[0]);
                    b.setGenre(data[1]);
                    b.setWibsite(data[2]);
                    b.setContactPerson(new Person()); 
                    b.getContactPerson().setFirst(data[3].substring(0, data[3].indexOf(" ")));
                    b.getContactPerson().setLast(data[3].substring(data[3].indexOf(" ")));
                    b.getContactPerson().setBirthDate(new BirthDate());
                    b.getContactPerson().getBirthDate().setDay(Integer.parseInt(data[4]));
                    b.getContactPerson().getBirthDate().setMonth(Integer.parseInt(data[5]));
                    b.getContactPerson().getBirthDate().setYear(Integer.parseInt(data[6]));
                    b.getContactPerson().setEmail(data[7]);
                    b.getContactPerson().setTelNum(data[8]);
                    b.getContactPerson().setCountry(data[9]);
                    b.getContactPerson().setCity(data[10]);
                    b.getContactPerson().setPostal(data[11]);
                    b.setEmail(data[12]);
                    b.setTelNum(data[13]);
                    b.setCountry(data[14]);
                    b.setCity(data[15]);
                    b.setPostal(data[16]);
                    adresses.add(b);
                }
                search();

            }

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_OpenMenuItemActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AderessBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AderessBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AderessBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AderessBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AderessBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lday;
    private javax.swing.JLabel LfirstName;
    private javax.swing.JLabel LlastName1;
    private javax.swing.JMenuItem OpenMenuItem;
    private javax.swing.ButtonGroup adressButtonGroup;
    private javax.swing.JComboBox<String> bcityComboBox1;
    private javax.swing.JComboBox<String> bcountryComboBox1;
    private javax.swing.JTextField bemailTextField1;
    private javax.swing.JLabel birthdayl;
    private javax.swing.JTextField bpostalCodeTexField1;
    private javax.swing.JTextField btelephoneNumberTExtField1;
    private javax.swing.JRadioButton businessRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cityComboBox;
    private javax.swing.JLabel contactPersonDatajLabel;
    private javax.swing.JComboBox<String> countryComboBox;
    private javax.swing.JTextField dayTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JTextField generTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lTelephone;
    private javax.swing.JLabel lTelephone1;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel lcity;
    private javax.swing.JLabel lcity1;
    private javax.swing.JLabel lcountry;
    private javax.swing.JLabel lcountry1;
    private javax.swing.JLabel lemail;
    private javax.swing.JLabel lemail1;
    private javax.swing.JLabel lmonth;
    private javax.swing.JLabel lpostal;
    private javax.swing.JLabel lpostal1;
    private javax.swing.JLabel lyear;
    private javax.swing.JTextField monthTextField;
    private javax.swing.JPanel person;
    private javax.swing.JRadioButton personRadioButton;
    private javax.swing.JTextField postalCodeTexField;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JPanel search;
    private javax.swing.JTextField searchAbout;
    private javax.swing.JList<String> searchRes;
    private javax.swing.JTextField telephoneNumberTExtField;
    private javax.swing.JTextField titleTextField;
    private javax.swing.JTextField websiteTextField;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables
}
