/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.aderessbook;

import java.util.ArrayList;

/**
 *
 * @author smart
 */
public class Dataadressbook extends javax.swing.JFrame {

    ArrayList<Data> adresses = new ArrayList<>();

//    /**
//     * Creates new form Dataadressbook
//     */
    public Dataadressbook() {
        initComponents();
    }

    public void display() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adressButtonGroup = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        person = new javax.swing.JPanel();
        LfirstName = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        LlastName1 = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        birthdayl = new javax.swing.JLabel();
        dayTextField = new javax.swing.JTextField();
        monthTextField = new javax.swing.JTextField();
        yearTextField = new javax.swing.JTextField();
        Lday = new javax.swing.JLabel();
        lmonth = new javax.swing.JLabel();
        lyear = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lcountry = new javax.swing.JLabel();
        countryComboBox = new javax.swing.JComboBox<>();
        lcity = new javax.swing.JLabel();
        cityComboBox = new javax.swing.JComboBox<>();
        lpostal = new javax.swing.JLabel();
        postalCodeTexField = new javax.swing.JTextField();
        lemail = new javax.swing.JLabel();
        generTextField = new javax.swing.JTextField();
        lTelephone = new javax.swing.JLabel();
        telephoneNumberTExtField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        websiteTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        titleTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        personRadioButton = new javax.swing.JRadioButton();
        businessRadioButton = new javax.swing.JRadioButton();
        search = new javax.swing.JPanel();
        searchAbout = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchRes = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LfirstName.setText("First name : ");

        lastNameTextField.setEnabled(false);

        LlastName1.setText("Last name : ");

        firstNameTextField.setEnabled(false);
        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });

        birthdayl.setText("Birthday:");

        dayTextField.setEnabled(false);

        monthTextField.setEnabled(false);

        yearTextField.setEnabled(false);
        yearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearTextFieldActionPerformed(evt);
            }
        });

        Lday.setText("Day");

        lmonth.setText("Month");

        lyear.setText("Year");

        lcountry.setText("Country :");

        countryComboBox.setEditable(true);
        countryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "country", "Palestine", "Jordan", "Iraq", "Kuwait", "Saudi Arabia", "Egypt", " ", " " }));
        countryComboBox.setEnabled(false);
        countryComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                countryComboBoxItemStateChanged(evt);
            }
        });

        lcity.setText("City :");

        cityComboBox.setEditable(true);
        cityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "City", "Hebron", "Ramallah", "Jericho", "Gaza", "Nablus", "Cairo", "Alexandria", "Luxor", "Hawally", "Fintas", "Al Jahra", "Al Farwaniyah", " " }));
        cityComboBox.setEnabled(false);
        cityComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cityComboBoxItemStateChanged(evt);
            }
        });

        lpostal.setText("Postal Code : ");

        postalCodeTexField.setEnabled(false);
        postalCodeTexField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postalCodeTexFieldActionPerformed(evt);
            }
        });

        lemail.setText("Email :");

        generTextField.setEnabled(false);

        lTelephone.setText("Telephone-Number");

        telephoneNumberTExtField.setEnabled(false);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        websiteTextField.setEnabled(false);

        jLabel3.setText("Title :");

        titleTextField.setEnabled(false);

        jLabel4.setText("Gener :");

        jLabel5.setText("Website :");

        emailTextField.setEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Adress Type : "));

        adressButtonGroup.add(personRadioButton);
        personRadioButton.setText("Person");
        personRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personRadioButtonActionPerformed(evt);
            }
        });

        adressButtonGroup.add(businessRadioButton);
        businessRadioButton.setText("Businiss ");
        businessRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                businessRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(personRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(businessRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personRadioButton)
                    .addComponent(businessRadioButton))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout personLayout = new javax.swing.GroupLayout(person);
        person.setLayout(personLayout);
        personLayout.setHorizontalGroup(
            personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addGap(20, 20, 20))
            .addGroup(personLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(personLayout.createSequentialGroup()
                        .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LfirstName)
                            .addComponent(LlastName1)
                            .addComponent(birthdayl, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(personLayout.createSequentialGroup()
                                .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lday, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(monthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lyear, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(135, 135, 135)
                        .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(generTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(websiteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(personLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personLayout.createSequentialGroup()
                        .addComponent(lpostal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(personLayout.createSequentialGroup()
                        .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lTelephone)
                            .addComponent(lemail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lcity, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lcountry, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailTextField)
                            .addGroup(personLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(postalCodeTexField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telephoneNumberTExtField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(countryComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cityComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(249, 249, 249))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(155, 155, 155))
        );
        personLayout.setVerticalGroup(
            personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LfirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LlastName1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(generTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personLayout.createSequentialGroup()
                        .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(Lday))
                            .addGroup(personLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lyear)
                                    .addComponent(lmonth))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(birthdayl)
                            .addComponent(dayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(websiteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lcountry)
                    .addComponent(countryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lcity))
                .addGap(25, 25, 25)
                .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lemail)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTelephone)
                    .addComponent(telephoneNumberTExtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lpostal)
                    .addComponent(postalCodeTexField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(121, 121, 121))
        );

        jTabbedPane2.addTab("ِAdress Form", person);

        searchAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAboutActionPerformed(evt);
            }
        });
        searchAbout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchAboutKeyPressed(evt);
            }
        });

        jLabel7.setText("Search here :");

        searchRes.setBorder(javax.swing.BorderFactory.createTitledBorder("Search results"));
        searchRes.setEnabled(false);
        jScrollPane1.setViewportView(searchRes);

        javax.swing.GroupLayout searchLayout = new javax.swing.GroupLayout(search);
        search.setLayout(searchLayout);
        searchLayout.setHorizontalGroup(
            searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchLayout.createSequentialGroup()
                .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jScrollPane2))
                    .addGroup(searchLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchAbout)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE))
                .addGap(221, 221, 221))
        );
        searchLayout.setVerticalGroup(
            searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchLayout.createSequentialGroup()
                .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(searchLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(searchAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(295, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Search", search);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void postalCodeTexFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postalCodeTexFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postalCodeTexFieldActionPerformed

    private void cityComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cityComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cityComboBoxItemStateChanged

    private void countryComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_countryComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_countryComboBoxItemStateChanged

    private void yearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTextFieldActionPerformed

    private void personRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personRadioButtonActionPerformed
        // TODO add your handling code here:

        firstNameTextField.setEnabled(personRadioButton.isSelected());
        lastNameTextField.setEnabled(personRadioButton.isSelected());
        dayTextField.setEnabled(personRadioButton.isSelected());
        monthTextField.setEnabled(personRadioButton.isSelected());
        yearTextField.setEnabled(personRadioButton.isSelected());
        countryComboBox.setEnabled(personRadioButton.isSelected());
        cityComboBox.setEnabled(personRadioButton.isSelected());
        emailTextField.setEnabled(personRadioButton.isSelected());
        postalCodeTexField.setEnabled(personRadioButton.isSelected());
        telephoneNumberTExtField.setEnabled(personRadioButton.isSelected());
        titleTextField.setEnabled(!personRadioButton.isSelected());
        generTextField.setEnabled(!personRadioButton.isSelected());
        websiteTextField.setEnabled(!personRadioButton.isSelected());
    }//GEN-LAST:event_personRadioButtonActionPerformed

    private void businessRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_businessRadioButtonActionPerformed
        // TODO add your handling code here:

        titleTextField.setEnabled(businessRadioButton.isSelected());
        generTextField.setEnabled(businessRadioButton.isSelected());
        websiteTextField.setEnabled(businessRadioButton.isSelected());
        countryComboBox.setEnabled(businessRadioButton.isSelected());
        cityComboBox.setEnabled(businessRadioButton.isSelected());
        emailTextField.setEnabled(businessRadioButton.isSelected());
        postalCodeTexField.setEnabled(businessRadioButton.isSelected());
        telephoneNumberTExtField.setEnabled(businessRadioButton.isSelected());
        firstNameTextField.setEnabled(businessRadioButton.isSelected());
        lastNameTextField.setEnabled(businessRadioButton.isSelected());
        dayTextField.setEnabled(businessRadioButton.isSelected());
        monthTextField.setEnabled(businessRadioButton.isSelected());
        yearTextField.setEnabled(businessRadioButton.isSelected());

    }//GEN-LAST:event_businessRadioButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (personRadioButton.isSelected()) {
            String firstName = firstNameTextField.getText();
            String lastName = lastNameTextField.getText();
            int day = Integer.parseInt(dayTextField.getText());
            int month = Integer.parseInt(monthTextField.getText());
            int year = Integer.parseInt(yearTextField.getText());
            String country = countryComboBox.getSelectedItem().toString();
            String city = cityComboBox.getSelectedItem().toString();
            String postalCode = postalCodeTexField.getText();
            String email = emailTextField.getText();
            String telephone = telephoneNumberTExtField.getText();
            BirthDate bd = new BirthDate(day, month, year);
            Person person = new Person(firstName, lastName, bd, country, city, email, postalCode, telephone);
            adresses.add(person);
            firstNameTextField.setText("");
            lastNameTextField.setText("");
            dayTextField.setText("");
            monthTextField.setText("");
            yearTextField.setText("");
            countryComboBox.setSelectedIndex(0);
            cityComboBox.setSelectedIndex(0);
            postalCodeTexField.setText("");
            emailTextField.setText("");
            telephoneNumberTExtField.setText("");

        } else {
            String country = countryComboBox.getSelectedItem().toString();
            String city = cityComboBox.getSelectedItem().toString();
            String postalCode = postalCodeTexField.getText();
            String email = emailTextField.getText();
            String telephone = telephoneNumberTExtField.getText();
            String title = titleTextField.getText();
            String gener = generTextField.getText();
            String wibsite = websiteTextField.getText();
            String firstName = firstNameTextField.getText();
            String lastName = lastNameTextField.getText();
            int day = Integer.parseInt(dayTextField.getText());
            int month = Integer.parseInt(monthTextField.getText());
            int year = Integer.parseInt(yearTextField.getText());
            BirthDate bd = new BirthDate(day, month, year);
            Person person = new Person(firstName, lastName, bd, country, city, email, postalCode, telephone);
            Bussinesses bussinesses = new Bussinesses(title, gener, wibsite, person);
            adresses.add(bussinesses);
            firstNameTextField.setText("");
            lastNameTextField.setText("");
            dayTextField.setText("");
            monthTextField.setText("");
            yearTextField.setText("");
            countryComboBox.setSelectedIndex(0);
            cityComboBox.setSelectedIndex(0);
            postalCodeTexField.setText("");
            emailTextField.setText("");
            telephoneNumberTExtField.setText("");
            titleTextField.setText("");
            generTextField.setText("");
            websiteTextField.setText("");

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void searchAboutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchAboutKeyPressed
        // TODO add your handling code here:
        String [] empty = new String[0] ;
        searchRes.setListData(empty);
        String searchParams = searchAbout.getText() ;
        System.out.println (searchParams);
        ArrayList <Data> searchResults = new ArrayList<>() ;
        for (Data d : adresses) {
            if (d instanceof Person) {
                Person p = (Person) d ;
                if (p.compareBy(searchParams))
                searchResults.add(p) ;
            }
            if (d instanceof Bussinesses) {
                Bussinesses b = (Bussinesses) d ;
                if (b.compareBy(searchParams))
                searchResults.add(b) ;
            }
        }
        String[] searchResultsList = new String[searchResults.size()] ;
        for (int i = 0; i < searchResults.size(); i++) {
            searchResultsList[i] = searchResults.get(i).getInfo();
        }
        System.out.println (searchResults.size()) ;
        searchRes.setListData(searchResultsList);

    }//GEN-LAST:event_searchAboutKeyPressed

    private void searchAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAboutActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_searchAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dataadressbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dataadressbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dataadressbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dataadressbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dataadressbook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lday;
    private javax.swing.JLabel LfirstName;
    private javax.swing.JLabel LlastName1;
    private javax.swing.ButtonGroup adressButtonGroup;
    private javax.swing.JLabel birthdayl;
    private javax.swing.JRadioButton businessRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cityComboBox;
    private javax.swing.JComboBox<String> countryComboBox;
    private javax.swing.JTextField dayTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JTextField generTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lTelephone;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel lcity;
    private javax.swing.JLabel lcountry;
    private javax.swing.JLabel lemail;
    private javax.swing.JLabel lmonth;
    private javax.swing.JLabel lpostal;
    private javax.swing.JLabel lyear;
    private javax.swing.JTextField monthTextField;
    private javax.swing.JPanel person;
    private javax.swing.JRadioButton personRadioButton;
    private javax.swing.JTextField postalCodeTexField;
    private javax.swing.JPanel search;
    private javax.swing.JTextField searchAbout;
    private javax.swing.JList<String> searchRes;
    private javax.swing.JTextField telephoneNumberTExtField;
    private javax.swing.JTextField titleTextField;
    private javax.swing.JTextField websiteTextField;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables
}
